### PR TITLE
fix move loading failed issue

### PR DESCRIPTION
**Pull request by lispking**

### CODE REVIEW

**Comment by Tzal3x** [comment]
Hey @lispking, thank you for the contribution! 🙏 

What's the issue you are facing exactly? In my machine I can install the extension without a problem.

**Comment by Tzal3x** [comment]
Deleting the old `grammars` directory resulted in the extension being installed successfully (at least it shows on the extensions tab). However I am opening `.move` files and it seems like it doesn't work, no highlights, no autocompletion etc. 

Please elaborate, otherwise I can't merge this.

**Comment by lispking** [comment]
It can't be installed on my computer. The version is: Zed 0.165.4.

1. the package names of the official plugins in Cargo are basically in the form of "zed_xxx", so it is recommended to make modifications here. 
2. The original name "move-zed-extension" couldn't be installed successfully on my computer. It can only be installed successfully after changing it to "move". If you want to install this version on your computer, you need to uninstall it first and then reinstall it so that the highlighting and prompts can be displayed. 
3. The old "grammars" directory was originally uploaded in your repository. I don't think it needs to be uploaded either. A new version has already been submitted in the.gitignore file. 
4. For the Rust code, it is recommended to put the implementation inside the "impl struct" just like the official ones. In this way, the implementation will look more standardized and the plugin will seem to be written by a professional team. 
5. Aha, I noticed that "testnet" was written for your coffee sponsorship here. It's recommended to change it to "mainnet". I've already made the modification casually.

**Comment by Tzal3x** [comment]
Awesome, it looks good now. Thank you for your answer @lispking, we can now merge this. 😄 

I just made a commit to bump the version to `v1.0.0`.

**Pull request merged**
